name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw  --batch-mode --update-snapshots verify

      - name: Perform release build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo $GITHUB_REF
          git switch -c release-temp
          git add -A
          git diff-index --quiet HEAD || git commit -m '[releng] auto-update'
          ./mvnw -B release:prepare release:perform
          git tag -f -a $RELEASE_VERSION
          git push -f --tags
